# Generated by Django 5.1.2 on 2025-02-01 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flip_card', '0006_leveldocuments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LevelArticles',
        ),
    ]
