# Generated by Django 5.1.2 on 2025-02-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='converted_image',
            field=models.ImageField(max_length=500, upload_to='converted_images/'),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='pdf_file',
            field=models.FileField(max_length=500, upload_to='pdfs/'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='dynamicDB.pdfdocument')),
            ],
        ),
    ]
