# Generated by Django 5.1.2 on 2025-04-18 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicDB', '0002_alter_pdfdocument_converted_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('order', models.IntegerField(default=0)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='dynamicDB.pdfdocument')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MainTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('chapters', models.ManyToManyField(related_name='main_topics', to='dynamicDB.chapter')),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_topics', to='dynamicDB.pdfdocument')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
