# Generated by Django 5.1.2 on 2025-04-08 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicDB', '0002_alter_pdfdocument_converted_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='is_textbook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='processing_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='pdf_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='dynamicDB.pdfdocument'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='dynamicDB.pdfdocument')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='dynamicDB.chapter'),
        ),
        migrations.CreateModel(
            name='ContentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_key_point', models.BooleanField(default=False)),
                ('simplified_text', models.TextField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_points', to='dynamicDB.topic')),
            ],
        ),
        migrations.CreateModel(
            name='GameContentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('SNAKE_LADDER', 'Snake and Ladder'), ('HOUSIE', 'Constitutional Housie'), ('SPINWHEEL', 'Spin Wheel'), ('FLIPCARD', 'Flip Card')], max_length=20)),
                ('difficulty', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_mappings', to='dynamicDB.contentpoint')),
            ],
            options={
                'unique_together': {('content_point', 'game_type')},
            },
        ),
    ]
