# Generated by Django 5.1.2 on 2025-04-18 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicDB', '0003_chapter_maintopic_delete_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dynamicDB.topicgroup')),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_groups', to='dynamicDB.pdfdocument')),
                ('topics', models.ManyToManyField(related_name='topic_groups', to='dynamicDB.maintopic')),
            ],
            options={
                'verbose_name': 'Topic Group',
                'verbose_name_plural': 'Topic Groups',
                'ordering': ['order'],
            },
        ),
    ]
