# Generated by Django 5.1.2 on 2025-04-18 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicDB', '0004_topicgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePDFSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamicDB.pdfdocument')),
            ],
            options={
                'verbose_name': 'Active PDF Selection',
                'verbose_name_plural': 'Active PDF Selections',
            },
        ),
    ]
