# Generated by Django 5.1.2 on 2025-04-18 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicDB', '0005_activepdfselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTopicGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now=True)),
                ('topic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_selections', to='dynamicDB.topicgroup')),
            ],
            options={
                'verbose_name': 'Active Topic Group',
                'verbose_name_plural': 'Active Topic Groups',
            },
        ),
    ]
