# Generated by Django 5.1.2 on 2025-04-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicDB', '0006_activetopicgroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_topics', models.ManyToManyField(related_name='summary_topics', to='dynamicDB.maintopic')),
                ('topic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_topics', to='dynamicDB.topicgroup')),
            ],
            options={
                'verbose_name': 'Summary Topic',
                'verbose_name_plural': 'Summary Topics',
                'ordering': ['order'],
            },
        ),
    ]
