# Generated by Django 5.1.2 on 2025-02-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0033_gameroom_part_gameroom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='part',
            field=models.CharField(default='Part 5', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(default='Executive', max_length=50),
        ),
    ]
