# Generated by Django 5.1.2 on 2025-04-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_ladder', '0020_cellbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_text', models.TextField(help_text='The constitutional law fact to display in the game')),
            ],
            options={
                'verbose_name': 'Game Fact',
                'verbose_name_plural': 'Game Facts',
            },
        ),
    ]
