# Generated by Django 5.1.2 on 2025-04-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_ladder', '0021_gamefact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellcontent',
            options={'ordering': ['topic']},
        ),
        migrations.AddField(
            model_name='cellcontent',
            name='source_id',
            field=models.IntegerField(blank=True, help_text='ID of the MainTopic this content relates to', null=True),
        ),
    ]
