# Generated by Django 5.1.5 on 2025-04-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangmangame',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hangmangame',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='total_correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='total_wrong_answers',
            field=models.IntegerField(default=0),
        ),
    ]
