# Generated by Django 5.1.2 on 2025-04-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hang', '0002_hangmangame_correct_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Question Categories',
            },
        ),
        migrations.CreateModel(
            name='OddOneOutQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL', 'Fill in the Blank'), ('MATCH', 'Match the Pairs'), ('TF', 'True/False'), ('ODD', 'Odd One Out'), ('CAT', 'Categorize'), ('SCRAMBLE', 'Word Unscramble')], max_length=10)),
                ('question_text', models.TextField()),
                ('difficulty', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hang.questioncategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL', 'Fill in the Blank'), ('MATCH', 'Match the Pairs'), ('TF', 'True/False'), ('ODD', 'Odd One Out'), ('CAT', 'Categorize'), ('SCRAMBLE', 'Word Unscramble')], max_length=10)),
                ('question_text', models.TextField()),
                ('difficulty', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hang.questioncategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchPairsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL', 'Fill in the Blank'), ('MATCH', 'Match the Pairs'), ('TF', 'True/False'), ('ODD', 'Odd One Out'), ('CAT', 'Categorize'), ('SCRAMBLE', 'Word Unscramble')], max_length=10)),
                ('question_text', models.TextField()),
                ('difficulty', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pairs', models.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hang.questioncategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FillBlankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL', 'Fill in the Blank'), ('MATCH', 'Match the Pairs'), ('TF', 'True/False'), ('ODD', 'Odd One Out'), ('CAT', 'Categorize'), ('SCRAMBLE', 'Word Unscramble')], max_length=10)),
                ('question_text', models.TextField()),
                ('difficulty', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(max_length=255)),
                ('hint_pattern', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hang.questioncategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategorizeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL', 'Fill in the Blank'), ('MATCH', 'Match the Pairs'), ('TF', 'True/False'), ('ODD', 'Odd One Out'), ('CAT', 'Categorize'), ('SCRAMBLE', 'Word Unscramble')], max_length=10)),
                ('question_text', models.TextField()),
                ('difficulty', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.JSONField()),
                ('items', models.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hang.questioncategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL', 'Fill in the Blank'), ('MATCH', 'Match the Pairs'), ('TF', 'True/False'), ('ODD', 'Odd One Out'), ('CAT', 'Categorize'), ('SCRAMBLE', 'Word Unscramble')], max_length=10)),
                ('question_text', models.TextField()),
                ('difficulty', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correct_answer', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hang.questioncategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordUnscrambleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL', 'Fill in the Blank'), ('MATCH', 'Match the Pairs'), ('TF', 'True/False'), ('ODD', 'Odd One Out'), ('CAT', 'Categorize'), ('SCRAMBLE', 'Word Unscramble')], max_length=10)),
                ('question_text', models.TextField()),
                ('difficulty', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scrambled_word', models.CharField(max_length=255)),
                ('correct_word', models.CharField(max_length=255)),
                ('hint', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hang.questioncategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
